# Generated by Django 5.2.8 on 2025-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_class', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('student_contact', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('sibling1_name', models.CharField(blank=True, max_length=255)),
                ('sibling1_school', models.CharField(blank=True, max_length=255)),
                ('sibling1_class', models.CharField(blank=True, max_length=100)),
                ('sibling2_name', models.CharField(blank=True, max_length=255)),
                ('sibling2_school', models.CharField(blank=True, max_length=255)),
                ('sibling2_class', models.CharField(blank=True, max_length=100)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_contact', models.CharField(max_length=20)),
                ('parent_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('competitions', models.JSONField(blank=True, default=list)),
                ('workshops', models.JSONField(blank=True, default=list)),
                ('payment_mode', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_screenshot', models.ImageField(upload_to='payments/')),
                ('payment_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
